compilation:
  cloud_properties:
    name: random
  network: services
  reuse_compilation_vms: true
  workers: 6

director_uuid: b02f8ab5-b63c-4f08-b144-89f96810a022

disk_pools:
- cloud_properties: {}
  disk_size: 100000
  name: mysql-persistent-disk

jobs:
- instances: 1
  name: proxy
  networks:
  - name: mysql
    static_ips:
    - 10.244.7.2
  properties:
    cluster_ips:
    - 10.244.7.6
    - 10.244.7.10
    - 10.244.7.14
    network_name: mysql
    proxy:
      api_force_https: null
      api_password: password
      api_username: username
      health_port: null
    syslog_aggregator: null
  release: cf-mysql
  resource_pool: proxy
  template: proxy
- instances: 3
  name: mysql
  networks:
  - name: mysql
    static_ips:
    - 10.244.7.6
    - 10.244.7.10
    - 10.244.7.14
  persistent_disk_pool: mysql-persistent-disk
  properties:
    admin_password: password
    cluster_ips:
    - 10.244.7.6
    - 10.244.7.10
    - 10.244.7.14
    max_heap_table_size: null
    network_name: mysql
    seeded_databases: null
    syslog_aggregator: null
    tmp_table_size: null
  release: cf-mysql
  resource_pool: mysql
  template: mysql
meta:
  environment: null
  syslog_aggregator: null
name: cf-warden-mysql

networks:
- name: services
  subnets:
  - cloud_properties:
      name: random
    range: 10.244.1.0/30
    reserved:
    - 10.244.1.1
    static:
    - 10.244.1.2
  - cloud_properties:
      name: random
    range: 10.244.1.4/30
    reserved:
    - 10.244.1.5
    static:
    - 10.244.1.6
  - cloud_properties:
      name: random
    range: 10.244.1.8/30
    reserved:
    - 10.244.1.9
    static:
    - 10.244.1.10
  - cloud_properties:
      name: random
    range: 10.244.1.12/30
    reserved:
    - 10.244.1.13
    static:
    - 10.244.1.14
  - cloud_properties:
      name: random
    range: 10.244.1.16/30
    reserved:
    - 10.244.1.17
    static:
    - 10.244.1.18
  - cloud_properties:
      name: random
    range: 10.244.1.20/30
    reserved:
    - 10.244.1.21
    static:
    - 10.244.1.22
  - cloud_properties:
      name: random
    range: 10.244.1.24/30
    reserved:
    - 10.244.1.25
    static:
    - 10.244.1.26
  - cloud_properties:
      name: random
    range: 10.244.1.28/30
    reserved:
    - 10.244.1.29
    static:
    - 10.244.1.30
  - cloud_properties:
      name: random
    range: 10.244.1.32/30
    reserved:
    - 10.244.1.33
    static:
    - 10.244.1.34
  - cloud_properties:
      name: random
    range: 10.244.1.36/30
    reserved:
    - 10.244.1.37
    static:
    - 10.244.1.38
  - cloud_properties:
      name: random
    range: 10.244.1.40/30
    reserved:
    - 10.244.1.41
    static:
    - 10.244.1.42
  - cloud_properties:
      name: random
    range: 10.244.1.44/30
    reserved:
    - 10.244.1.45
    static:
    - 10.244.1.46
  - cloud_properties:
      name: random
    range: 10.244.1.48/30
    reserved:
    - 10.244.1.49
    static:
    - 10.244.1.50
  - cloud_properties:
      name: random
    range: 10.244.1.52/30
    reserved:
    - 10.244.1.53
    static:
    - 10.244.1.54
  - cloud_properties:
      name: random
    range: 10.244.1.56/30
    reserved:
    - 10.244.1.57
    static:
    - 10.244.1.58
  - cloud_properties:
      name: random
    range: 10.244.1.60/30
    reserved:
    - 10.244.1.61
    static:
    - 10.244.1.62
  - cloud_properties:
      name: random
    range: 10.244.1.64/30
    reserved:
    - 10.244.1.65
    static:
    - 10.244.1.66
  - cloud_properties:
      name: random
    range: 10.244.1.68/30
    reserved:
    - 10.244.1.69
    static:
    - 10.244.1.70
  - cloud_properties:
      name: random
    range: 10.244.1.72/30
    reserved:
    - 10.244.1.73
    static:
    - 10.244.1.74
  - cloud_properties:
      name: random
    range: 10.244.1.76/30
    reserved:
    - 10.244.1.77
    static:
    - 10.244.1.78
  - cloud_properties:
      name: random
    range: 10.244.1.80/30
    reserved:
    - 10.244.1.81
    static:
    - 10.244.1.82
  - cloud_properties:
      name: random
    range: 10.244.1.84/30
    reserved:
    - 10.244.1.85
    static:
    - 10.244.1.86
  - cloud_properties:
      name: random
    range: 10.244.1.88/30
    reserved:
    - 10.244.1.89
    static:
    - 10.244.1.90
  - cloud_properties:
      name: random
    range: 10.244.1.92/30
    reserved:
    - 10.244.1.93
    static:
    - 10.244.1.94
  - cloud_properties:
      name: random
    range: 10.244.1.96/30
    reserved:
    - 10.244.1.97
    static:
    - 10.244.1.98
  - cloud_properties:
      name: random
    range: 10.244.1.100/30
    reserved:
    - 10.244.1.101
    static:
    - 10.244.1.102
  - cloud_properties:
      name: random
    range: 10.244.1.104/30
    reserved:
    - 10.244.1.105
    static:
    - 10.244.1.106
  - cloud_properties:
      name: random
    range: 10.244.1.108/30
    reserved:
    - 10.244.1.109
    static:
    - 10.244.1.110
  - cloud_properties:
      name: random
    range: 10.244.1.112/30
    reserved:
    - 10.244.1.113
    static:
    - 10.244.1.114
  - cloud_properties:
      name: random
    range: 10.244.1.116/30
    reserved:
    - 10.244.1.117
    static:
    - 10.244.1.118
  - cloud_properties:
      name: random
    range: 10.244.1.120/30
    reserved:
    - 10.244.1.121
    static:
    - 10.244.1.122
  - cloud_properties:
      name: random
    range: 10.244.1.124/30
    reserved:
    - 10.244.1.125
    static:
    - 10.244.1.126
  - cloud_properties:
      name: random
    range: 10.244.1.128/30
    reserved:
    - 10.244.1.129
    static: []
  - cloud_properties:
      name: random
    range: 10.244.1.132/30
    reserved:
    - 10.244.1.133
    static: []
  - cloud_properties:
      name: random
    range: 10.244.1.136/30
    reserved:
    - 10.244.1.137
    static: []
  - cloud_properties:
      name: random
    range: 10.244.1.140/30
    reserved:
    - 10.244.1.141
    static: []
  - cloud_properties:
      name: random
    range: 10.244.1.144/30
    reserved:
    - 10.244.1.145
    static: []
  - cloud_properties:
      name: random
    range: 10.244.1.148/30
    reserved:
    - 10.244.1.149
    static: []
  - cloud_properties:
      name: random
    range: 10.244.1.152/30
    reserved:
    - 10.244.1.153
    static: []
  - cloud_properties:
      name: random
    range: 10.244.1.156/30
    reserved:
    - 10.244.1.157
    static: []
  - cloud_properties:
      name: random
    range: 10.244.1.160/30
    reserved:
    - 10.244.1.161
    static: []
  - cloud_properties:
      name: random
    range: 10.244.1.164/30
    reserved:
    - 10.244.1.165
    static: []
  - cloud_properties:
      name: random
    range: 10.244.1.168/30
    reserved:
    - 10.244.1.169
    static: []
  - cloud_properties:
      name: random
    range: 10.244.1.172/30
    reserved:
    - 10.244.1.173
    static: []
  - cloud_properties:
      name: random
    range: 10.244.1.176/30
    reserved:
    - 10.244.1.177
    static: []
  - cloud_properties:
      name: random
    range: 10.244.1.180/30
    reserved:
    - 10.244.1.181
    static: []
  - cloud_properties:
      name: random
    range: 10.244.1.184/30
    reserved:
    - 10.244.1.185
    static: []
  - cloud_properties:
      name: random
    range: 10.244.1.188/30
    reserved:
    - 10.244.1.189
    static: []
  - cloud_properties:
      name: random
    range: 10.244.1.192/30
    reserved:
    - 10.244.1.193
    static: []
  - cloud_properties:
      name: random
    range: 10.244.1.196/30
    reserved:
    - 10.244.1.197
    static: []
  - cloud_properties:
      name: random
    range: 10.244.1.200/30
    reserved:
    - 10.244.1.201
    static: []
  - cloud_properties:
      name: random
    range: 10.244.1.204/30
    reserved:
    - 10.244.1.205
    static: []
  - cloud_properties:
      name: random
    range: 10.244.1.208/30
    reserved:
    - 10.244.1.209
    static: []
  - cloud_properties:
      name: random
    range: 10.244.1.212/30
    reserved:
    - 10.244.1.213
    static: []
  - cloud_properties:
      name: random
    range: 10.244.1.216/30
    reserved:
    - 10.244.1.217
    static: []
  - cloud_properties:
      name: random
    range: 10.244.1.220/30
    reserved:
    - 10.244.1.221
    static: []
  - cloud_properties:
      name: random
    range: 10.244.1.224/30
    reserved:
    - 10.244.1.225
    static: []
  - cloud_properties:
      name: random
    range: 10.244.1.228/30
    reserved:
    - 10.244.1.229
    static: []
  - cloud_properties:
      name: random
    range: 10.244.1.232/30
    reserved:
    - 10.244.1.233
    static: []
  - cloud_properties:
      name: random
    range: 10.244.1.236/30
    reserved:
    - 10.244.1.237
    static: []
  - cloud_properties:
      name: random
    range: 10.244.1.240/30
    reserved:
    - 10.244.1.241
    static: []
  - cloud_properties:
      name: random
    range: 10.244.1.244/30
    reserved:
    - 10.244.1.245
    static: []
  - cloud_properties:
      name: random
    range: 10.244.1.248/30
    reserved:
    - 10.244.1.249
    static: []
  - cloud_properties:
      name: random
    range: 10.244.1.252/30
    reserved:
    - 10.244.1.253
    static: []
- name: mysql
  subnets:
  - cloud_properties:
      name: random
    range: 10.244.7.0/30
    reserved:
    - 10.244.7.1
    static:
    - 10.244.7.2
  - cloud_properties:
      name: random
    range: 10.244.7.4/30
    reserved:
    - 10.244.7.5
    static:
    - 10.244.7.6
  - cloud_properties:
      name: random
    range: 10.244.7.8/30
    reserved:
    - 10.244.7.9
    static:
    - 10.244.7.10
  - cloud_properties:
      name: random
    range: 10.244.7.12/30
    reserved:
    - 10.244.7.13
    static:
    - 10.244.7.14
  - cloud_properties:
      name: random
    range: 10.244.7.16/30
    reserved:
    - 10.244.7.17
    static:
    - 10.244.7.18
  - cloud_properties:
      name: random
    range: 10.244.7.20/30
    reserved:
    - 10.244.7.21
    static:
    - 10.244.7.22
  - cloud_properties:
      name: random
    range: 10.244.7.24/30
    reserved:
    - 10.244.7.25
    static:
    - 10.244.7.26
  - cloud_properties:
      name: random
    range: 10.244.7.28/30
    reserved:
    - 10.244.7.29
    static:
    - 10.244.7.30
  - cloud_properties:
      name: random
    range: 10.244.7.32/30
    reserved:
    - 10.244.7.33
    static:
    - 10.244.7.34
  - cloud_properties:
      name: random
    range: 10.244.7.36/30
    reserved:
    - 10.244.7.37
    static:
    - 10.244.7.38
  - cloud_properties:
      name: random
    range: 10.244.7.40/30
    reserved:
    - 10.244.7.41
    static:
    - 10.244.7.42
  - cloud_properties:
      name: random
    range: 10.244.7.44/30
    reserved:
    - 10.244.7.45
    static:
    - 10.244.7.46
  - cloud_properties:
      name: random
    range: 10.244.7.48/30
    reserved:
    - 10.244.7.49
    static:
    - 10.244.7.50
  - cloud_properties:
      name: random
    range: 10.244.7.52/30
    reserved:
    - 10.244.7.53
    static:
    - 10.244.7.54
  - cloud_properties:
      name: random
    range: 10.244.7.56/30
    reserved:
    - 10.244.7.57
    static:
    - 10.244.7.58
  - cloud_properties:
      name: random
    range: 10.244.7.60/30
    reserved:
    - 10.244.7.61
    static:
    - 10.244.7.62
  - cloud_properties:
      name: random
    range: 10.244.7.64/30
    reserved:
    - 10.244.7.65
    static:
    - 10.244.7.66
  - cloud_properties:
      name: random
    range: 10.244.7.68/30
    reserved:
    - 10.244.7.69
    static:
    - 10.244.7.70
  - cloud_properties:
      name: random
    range: 10.244.7.72/30
    reserved:
    - 10.244.7.73
    static:
    - 10.244.7.74
  - cloud_properties:
      name: random
    range: 10.244.7.76/30
    reserved:
    - 10.244.7.77
    static:
    - 10.244.7.78
  - cloud_properties:
      name: random
    range: 10.244.7.80/30
    reserved:
    - 10.244.7.81
    static:
    - 10.244.7.82
  - cloud_properties:
      name: random
    range: 10.244.7.84/30
    reserved:
    - 10.244.7.85
    static:
    - 10.244.7.86
  - cloud_properties:
      name: random
    range: 10.244.7.88/30
    reserved:
    - 10.244.7.89
    static:
    - 10.244.7.90
  - cloud_properties:
      name: random
    range: 10.244.7.92/30
    reserved:
    - 10.244.7.93
    static:
    - 10.244.7.94
  - cloud_properties:
      name: random
    range: 10.244.7.96/30
    reserved:
    - 10.244.7.97
    static:
    - 10.244.7.98
  - cloud_properties:
      name: random
    range: 10.244.7.100/30
    reserved:
    - 10.244.7.101
    static:
    - 10.244.7.102
  - cloud_properties:
      name: random
    range: 10.244.7.104/30
    reserved:
    - 10.244.7.105
    static:
    - 10.244.7.106
  - cloud_properties:
      name: random
    range: 10.244.7.108/30
    reserved:
    - 10.244.7.109
    static:
    - 10.244.7.110
  - cloud_properties:
      name: random
    range: 10.244.7.112/30
    reserved:
    - 10.244.7.113
    static:
    - 10.244.7.114
  - cloud_properties:
      name: random
    range: 10.244.7.116/30
    reserved:
    - 10.244.7.117
    static:
    - 10.244.7.118
  - cloud_properties:
      name: random
    range: 10.244.7.120/30
    reserved:
    - 10.244.7.121
    static:
    - 10.244.7.122
  - cloud_properties:
      name: random
    range: 10.244.7.124/30
    reserved:
    - 10.244.7.125
    static:
    - 10.244.7.126
  - cloud_properties:
      name: random
    range: 10.244.7.128/30
    reserved:
    - 10.244.7.129
    static: []
  - cloud_properties:
      name: random
    range: 10.244.7.132/30
    reserved:
    - 10.244.7.133
    static: []
  - cloud_properties:
      name: random
    range: 10.244.7.136/30
    reserved:
    - 10.244.7.137
    static: []
  - cloud_properties:
      name: random
    range: 10.244.7.140/30
    reserved:
    - 10.244.7.141
    static: []
  - cloud_properties:
      name: random
    range: 10.244.7.144/30
    reserved:
    - 10.244.7.145
    static: []
  - cloud_properties:
      name: random
    range: 10.244.7.148/30
    reserved:
    - 10.244.7.149
    static: []
  - cloud_properties:
      name: random
    range: 10.244.7.152/30
    reserved:
    - 10.244.7.153
    static: []
  - cloud_properties:
      name: random
    range: 10.244.7.156/30
    reserved:
    - 10.244.7.157
    static: []
  - cloud_properties:
      name: random
    range: 10.244.7.160/30
    reserved:
    - 10.244.7.161
    static: []
  - cloud_properties:
      name: random
    range: 10.244.7.164/30
    reserved:
    - 10.244.7.165
    static: []
  - cloud_properties:
      name: random
    range: 10.244.7.168/30
    reserved:
    - 10.244.7.169
    static: []
  - cloud_properties:
      name: random
    range: 10.244.7.172/30
    reserved:
    - 10.244.7.173
    static: []
  - cloud_properties:
      name: random
    range: 10.244.7.176/30
    reserved:
    - 10.244.7.177
    static: []
  - cloud_properties:
      name: random
    range: 10.244.7.180/30
    reserved:
    - 10.244.7.181
    static: []
  - cloud_properties:
      name: random
    range: 10.244.7.184/30
    reserved:
    - 10.244.7.185
    static: []
  - cloud_properties:
      name: random
    range: 10.244.7.188/30
    reserved:
    - 10.244.7.189
    static: []
  - cloud_properties:
      name: random
    range: 10.244.7.192/30
    reserved:
    - 10.244.7.193
    static: []
  - cloud_properties:
      name: random
    range: 10.244.7.196/30
    reserved:
    - 10.244.7.197
    static: []
  - cloud_properties:
      name: random
    range: 10.244.7.200/30
    reserved:
    - 10.244.7.201
    static: []
  - cloud_properties:
      name: random
    range: 10.244.7.204/30
    reserved:
    - 10.244.7.205
    static: []
  - cloud_properties:
      name: random
    range: 10.244.7.208/30
    reserved:
    - 10.244.7.209
    static: []
  - cloud_properties:
      name: random
    range: 10.244.7.212/30
    reserved:
    - 10.244.7.213
    static: []
  - cloud_properties:
      name: random
    range: 10.244.7.216/30
    reserved:
    - 10.244.7.217
    static: []
  - cloud_properties:
      name: random
    range: 10.244.7.220/30
    reserved:
    - 10.244.7.221
    static: []
  - cloud_properties:
      name: random
    range: 10.244.7.224/30
    reserved:
    - 10.244.7.225
    static: []
  - cloud_properties:
      name: random
    range: 10.244.7.228/30
    reserved:
    - 10.244.7.229
    static: []
  - cloud_properties:
      name: random
    range: 10.244.7.232/30
    reserved:
    - 10.244.7.233
    static: []
  - cloud_properties:
      name: random
    range: 10.244.7.236/30
    reserved:
    - 10.244.7.237
    static: []
  - cloud_properties:
      name: random
    range: 10.244.7.240/30
    reserved:
    - 10.244.7.241
    static: []
  - cloud_properties:
      name: random
    range: 10.244.7.244/30
    reserved:
    - 10.244.7.245
    static: []
  - cloud_properties:
      name: random
    range: 10.244.7.248/30
    reserved:
    - 10.244.7.249
    static: []
  - cloud_properties:
      name: random
    range: 10.244.7.252/30
    reserved:
    - 10.244.7.253
    static: []

releases:
- name: cf-mysql
  version: latest

resource_pools:
- cloud_properties:
    name: random
  name: mysql
  network: mysql
  stemcell:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: latest
- cloud_properties:
    name: random
  name: proxy
  network: mysql
  stemcell:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: latest
update:
  canaries: 1
  canary_watch_time: 30000-600000
  max_in_flight: 1
  update_watch_time: 30000-600000
